const bot_dictionary = [
  {key: "ありがとう", ans: "どういたしまして！"},
  {key: "おはよう", ans: "おはようございます！"},
  {key: "こんにちは", ans: "こんにちは！"},
  {key: "こんばんは", ans: "こんばんは！"},
  {key: "初めまして", ans: "初めまして！"},
  {key: "元気", ans: "とても元気です！"},
  {key: "君の名前", ans: "ぼくはどく太！獨協大学のイメージキャラクターです！"},
  {key: "君は誰", ans: "ぼくはどく太！獨協大学のイメージキャラクターです！"},
  {key: "あなたの名前", ans: "ぼくはどく太！獨協大学のイメージキャラクターです！"},
  {key: "あなたは誰", ans: "ぼくはどく太！獨協大学のイメージキャラクターです！"},
  {key: "よろしく", ans: "よろしくお願いします！"},
  {key: "どく太", ans: "はい！"},
  {key: "ドクタ", ans: "はい！"},
  {key: "どくた", ans: "はい！"},
  {key: "何歳", ans: "1999年生まれの22歳だよ！"},
  {key: "創設者", ans: "獨協大学の創設者・初代学長は天野貞祐先生だよ！<br><br><a href='https://www.dokkyo.ac.jp/about/outline/history/founder/'>創設者・天野貞祐について</a>"},
  {key: "初代学長", ans: "獨協大学の創設者・初代学長は天野貞祐先生だよ！<br><br><a href='https://www.dokkyo.ac.jp/about/outline/history/founder/'>創設者・天野貞祐について</a>"},
  {key: "学長", ans: "獨協大学の学長は山路朝彦学長だよ！<br><br><a href='https://www.dokkyo.ac.jp/about/outline/message.html'>学長メッセージを見る</a>"},
  {key: "外国語学部", ans: "外国語学部には以下の学科があるよ！<br><br>・ドイツ語学科<br>・英語学科<br>・フランス語学科<br>・交流文化学科<br><br><a href='https://www.dokkyo.ac.jp/academics/undergraduate/foreign/'>外国語学部についてはこちら</a>"},
  {key: "国際教養学部", ans: "外国語学部には以下の学科があるよ！<br><br>・ドイツ語学科<br>・英語学科<br>・フランス語学科<br>・交流文化学科<br><br><a href='https://www.dokkyo.ac.jp/academics/undergraduate/culture/'>国際教養学部についてはこちら</a>"},
  {key: "経済学部", ans: "経済学部には以下の学科があるよ！<br><br>・経済学科<br>・経営学科<br>・国際環境経済学科<br><br><a href='https://www.dokkyo.ac.jp/academics/undergraduate/economics/'>経済学部についてはこちら</a>"},
  {key: "法学部", ans: "法学部には以下の学科があるよ！<br><br>・法律学科<br>・国際関係法学科<br>・総合政策学科<br><br><a href='https://www.dokkyo.ac.jp/academics/undergraduate/law/'>法学部についてはこちら</a>"},
  {key: "学部", ans: "獨協大学には以下の学部があるよ！<br><br>・外国語学部<br>・国際教養学部<br>・経済学部<br>・法学部<br><br><a href='https://www.dokkyo.ac.jp/academics/'>学部学科・大学院についてはこちら</a>"},
  {key: "校章", ans: "獨協大学の校章はフラクトゥールの“D”を象ったものだよ！"},
  {key: "イメージカラー", ans: "獨協大学のイメージカラーはDOKKYOブルーだよ！"},
  {key: "校歌", ans: "獨協大学校歌は、作詞：小池辰雄 作曲：萬澤遼だよ！"},
  {key: "応援歌", ans: "獨協大学の応援歌「覇者」は、作詞：谷川正秋 作曲：野田隆造だよ！"},
  {key: "キャッチコピー", ans: "獨協大学のキャッチコピーは「一生の友達とパスポートのスタンプが増えました」だよ！"},
  {key: "最寄駅", ans: "獨協大学の最寄駅は獨協大学前駅（東武スカイツリーライン）だよ！"},
  {key: "最寄り駅", ans: "獨協大学の最寄駅は獨協大学前駅（東武スカイツリーライン）だよ！"},
  {key: "教職員食堂", ans: "教職員用の食堂は、学生も利用可能です。<br>利用可能な時間帯、メニューなどの詳細はPortaⅡの新着掲示>お知らせ・ご案内>「学生食堂・教職員食堂の営業再開について」で確認できます。"},
  {key: "学食", ans: "現在、学生食堂の食事スペースは一部解放されており、平日は10時から17時までの間、自由に利用することが可能です。<br>学生食堂への入室時の学生証タッチ、食堂内での会話の自粛にご協力ください。<br>学生食堂では、10月11日(月)からの弁当販売が予定されています(10月7日現在の情報)"},
  {key: "学生食堂", ans: "現在、学生食堂の食事スペースは一部解放されており、平日は10時から17時までの間、自由に利用することが可能です。<br>学生食堂への入室時の学生証タッチ、食堂内での会話の自粛にご協力ください。<br>学生食堂では、10月11日(月)からの弁当販売が予定されています(10月7日現在の情報)"},
  {key: "棟", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "aとう", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "Aとう", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "eとう", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "Eとう", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "wとう", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "Wとう", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "4とう", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "6とう", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "天野貞祐記念館", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "35周年記念館", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "学生センター", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "学セン", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "グラウンド", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "キャンパス", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "場所", ans: "キャンパス内の各施設の場所については、学内マップを見てね！<br><br><a href='../map/map.gn.html'>学内マップを見る</a>"},
  {key: "飲食店", ans: "獨協大学周辺の飲食店については、学外マップを見てね！<br><br><a href='../map/map.gg.html'>学内マップを見る</a>"},
  {key: "部活", ans: "獨協大学の部活については、ゼミ・部活動紹介を見てね！<br><br><a href='../activity'>ゼミ・部活動紹介を見る</a>"},
  {key: "サークル", ans: "獨協大学のサークルについては、ゼミ・部活動紹介を見てね！<br><br><a href='../activity'>ゼミ・部活動紹介を見る</a>"},
  {key: "ゼミ", ans: "獨協大学のゼミについては、ゼミ・部活動紹介を見てね！<br><br><a href='../activity'>ゼミ・部活動紹介を見る</a>"},
  {key: "活動", ans: "獨協大学の活動については、ゼミ・部活動紹介を見てね！<br><br><a href='../activity'>ゼミ・部活動紹介を見る</a>"},
  {key: "アクセス", ans: "獨協大学へのアクセス方法は<a href='https://www.dokkyo.ac.jp/about/outline/access.html'>こちら</a>"},
  {key: "施設", ans: "2021年度の学生生活支援施設の営業については<a href='https://www.dokkyo.ac.jp/information/2021/20210401004377.html'>こちら</a>"},
  {key: "図書館", ans: "図書館の利用スケジュールの確認や蔵書検索などは<a href='https://www.dokkyo.ac.jp/library/'>こちら</a>"},
  {key: "コロナ", ans: "新型コロナウイルス関連の大学の情報は、大学HPやPorTaⅡに掲載されている情報が最新の情報です<br>掲載内容に変更があれば随時更新されますので、こまめに確認をお願いいたします<br><br><a href='https://www.dokkyo.ac.jp/'>大学HPはこちら</a>"},
  {key: "COVID", ans: "新型コロナウイルス関連の大学の情報は、大学HPやPorTaⅡに掲載されている情報が最新の情報です<br>掲載内容に変更があれば随時更新されますので、こまめに確認をお願いいたします<br><br><a href='https://www.dokkyo.ac.jp/'>大学HPはこちら</a>"},
  {key: "covid", ans: "新型コロナウイルス関連の大学の情報は、大学HPやPorTaⅡに掲載されている情報が最新の情報です<br>掲載内容に変更があれば随時更新されますので、こまめに確認をお願いいたします<br><br><a href='https://www.dokkyo.ac.jp/'>大学HPはこちら</a>"},
  {key: "シラバス", ans: "各講義のシラバスは<a href='https://www.dokkyo.ac.jp/research/syllabus/'>こちら</a>"},
  {key: "忘れ", ans: "「パスワードを忘れた際の対応」に関する回答を表示します。<br><br>まず、大学が提供しているwebメールのアドレス(Webメールのパスワードを忘れてログイン出来ない場合は他のメールアドレスからで構いません)から、以下の内容を記載したメールを「教育研究支援センター」に連絡してください。<br><br>1.学籍番号<br>2.フルネーム<br>3.保証人の電話番号<br>4.(ウェブサイト名)のパスワードを忘れました<br><br>上記4点を記載したメールを以下の宛先へ送信してください。<br><br><a href='mailto:pc-qa@ml.dokkyo.ac.jp'>pc-qa@ml.dokkyo.ac.jp</a><br><br>こちらでメールの内容を確認後、パスワードが記載されたPDFファイルをダウンロードするためのURLとそのPDFファイルを開くためのパスワードを獨協大学Webメールに送信いたしますのでダウンロードをお試しください。"},
  {key: "パスワード", ans: "「パスワードを忘れた際の対応」に関する回答を表示します。<br><br>まず、大学が提供しているwebメールのアドレス(Webメールのパスワードを忘れてログイン出来ない場合は他のメールアドレスからで構いません)から、以下の内容を記載したメールを「教育研究支援センター」に連絡してください。<br><br>1.学籍番号<br>2.フルネーム<br>3.保証人の電話番号<br>4.(ウェブサイト名)のパスワードを忘れました<br><br>上記4点を記載したメールを以下の宛先へ送信してください。<br><br><a href='mailto:pc-qa@ml.dokkyo.ac.jp'>pc-qa@ml.dokkyo.ac.jp</a><br><br>こちらでメールの内容を確認後、パスワードが記載されたPDFファイルをダウンロードするためのURLとそのPDFファイルを開くためのパスワードを獨協大学Webメールに送信いたしますのでダウンロードをお試しください。"},
  {key: "PorTa", ans: "<a href='https://dreams.dokkyo.ac.jp/campusweb/campusportal.do' data-sp-href='https://dreams.dokkyo.ac.jp/campusweb/campussmart.do?locale=ja_JP'>PorTaⅡはこちら</a>"},
  {key: "porta", ans: "<a href='https://dreams.dokkyo.ac.jp/campusweb/campusportal.do'>PorTaⅡはこちら</a>"},
  {key: "ポルタ", ans: "<a href='https://dreams.dokkyo.ac.jp/campusweb/campusportal.do'>PorTaⅡはこちら</a>"},
  {key: "ぽるた", ans: "<a href='https://dreams.dokkyo.ac.jp/campusweb/campusportal.do'>PorTaⅡはこちら</a>"},
  {key: "manaba", ans: "<a href='https://manaba.dokkyo.ac.jp/'>manabaはこちら</a>"},
  {key: "マナバ", ans: "<a href='https://manaba.dokkyo.ac.jp/'>manabaはこちら</a>"},
  {key: "まなば", ans: "<a href='https://manaba.dokkyo.ac.jp/'>manabaはこちら</a>"},
  {key: "manabaの使い方", ans: "<a href='https://www.dokkyo.ac.jp/research/ict/manaba.html'>manabaの使い方についてはこちら</a>"},
  {key: "doc", ans: "<a href='https://bb.dokkyo.ac.jp/webapps/portal/execute/tabs/tabAction?tab_tab_group_id=_12_1'>My DOCはこちら</a>"},
  {key: "DOC", ans: "<a href='https://bb.dokkyo.ac.jp/webapps/portal/execute/tabs/tabAction?tab_tab_group_id=_12_1'>My DOCはこちら</a>"},
  {key: "マイドック", ans: "<a href='https://bb.dokkyo.ac.jp/webapps/portal/execute/tabs/tabAction?tab_tab_group_id=_12_1'>My DOCはこちら</a>"},
  {key: "まいどっく", ans: "<a href='https://bb.dokkyo.ac.jp/webapps/portal/execute/tabs/tabAction?tab_tab_group_id=_12_1'>My DOCはこちら</a>"},
  {key: "メール", ans: "<a href='https://webmail.dokkyo.ac.jp/cgi-bin/index.cgi'>Webメールはこちら</a><br><br>大学のWebメールに関する質問は、教育研究支援センターへ直接お問い合わせください。本人確認を兼ねて、大学から配布されたメールアドレスからの連絡をお願いします。<br>教育支援センターのメールアドレスはこちらです。<br><br><a href='mailto:pc-qa@ml.dokkyo.ac.jp'>pc-qa@ml.dokkyo.ac.jp</a>"},
  {key: "めーる", ans: "<a href='https://webmail.dokkyo.ac.jp/cgi-bin/index.cgi'>Webメールはこちら</a><br><br>大学のWebメールに関する質問は、教育研究支援センターへ直接お問い合わせください。本人確認を兼ねて、大学から配布されたメールアドレスからの連絡をお願いします。<br>教育支援センターのメールアドレスはこちらです。<br><br><a href='mailto:pc-qa@ml.dokkyo.ac.jp'>pc-qa@ml.dokkyo.ac.jp</a>"},
  {key: "mail", ans: "<a href='https://webmail.dokkyo.ac.jp/cgi-bin/index.cgi'>Webメールはこちら</a><br><br>大学のWebメールに関する質問は、教育研究支援センターへ直接お問い合わせください。本人確認を兼ねて、大学から配布されたメールアドレスからの連絡をお願いします。<br>教育支援センターのメールアドレスはこちらです。<br><br><a href='mailto:pc-qa@ml.dokkyo.ac.jp'>pc-qa@ml.dokkyo.ac.jp</a>"},
  {key: "削除", ans: "履修登録した科目の削除は、指定された期間のみ可能になります。削除が可能な時期については決定次第、PorTaⅡに掲示されます。"},
  {key: "履修", ans: "履修登録に関する情報は、大学HPやPorTaⅡに掲載されている情報が最新の情報です。こまめに確認をお願いいたします。<br><br><a href='https://www.dokkyo.ac.jp/'>大学HPはこちら</a><br><br><a href='https://dreams.dokkyo.ac.jp/campusweb/campusportal.do'>PorTaⅡはこちら</a>"},
  {key: "講義", ans: "授業形式は科目ごとに異なり、それぞれの科目の担当教員が形式を指定します。<br>シラバスをご確認の上、不明点は担当教員にお問い合わせください。<br><br><a href='https://www.dokkyo.ac.jp/research/syllabus/'>シラバスはこちら</a>"},
  {key: "遠隔", ans: "<a href='https://www.dokkyo.ac.jp/research/ict/'>遠隔授業マニュアルはこちら</a>"},
  {key: "オンライン", ans: "<a href='https://www.dokkyo.ac.jp/research/ict/'>遠隔授業マニュアルはこちら</a>"},
  {key: "授業", ans: "授業形式は科目ごとに異なり、それぞれの科目の担当教員が形式を指定します。<br>シラバスをご確認の上、不明点は担当教員にお問い合わせください。<br><br><a href='https://www.dokkyo.ac.jp/research/syllabus/'>シラバスはこちら</a>"},
  {key: "教科書", ans: "教科書販売に関するご質問は、ぶっくぎゃらりぃDUOへ直接お問い合わせください。"},
  {key: "自習", ans: "現在構内で利用できる自習スペースは、「自習スペースMAP」に記載されています。自習スペースMAPは天野貞祐記念館(通称A棟)2階と3階にあるセミナースペース入り口に置いてあるので、ご自由にお持ちください。"},
  {key: "学生証", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/registrar/card.html'>学生証についてはこちら</a>"},
  {key: "通学証明書", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/registrar/concession_pass.html'>通学証明書についてはこちら</a>"},
  {key: "学割証", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/registrar/concession_pass.html'>学割証についてはこちら</a>"},
  {key: "住所変更", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/registrar/address_change.html'>住所変更についてはこちら</a>"},
  {key: "保証人", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/registrar/address_change.html'>保証人についてはこちら</a>"},
  {key: "本籍地", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/registrar/address_change.html'>学生の氏名・本籍地等 訂正・変更届についてはこちら</a>"},
  {key: "休学", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/registrar/absence_dropout.html'>休学・復学・退学についてはこちら</a>"},
  {key: "復学", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/registrar/absence_dropout.html'>休学・復学・退学についてはこちら</a>"},
  {key: "退学", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/registrar/absence_dropout.html'>休学・復学・退学についてはこちら</a>"},
  {key: "改姓", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/registrar/alumni_change.html'>卒業生住所変更・改姓の届出についてはこちら</a>"},
  {key: "成績通知表", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/registrar/rd.html'>成績通知表の開示についてはこちら</a>"},
  {key: "証明書", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/registrar/certificate.html'>証明書発行についてはこちら</a>"},
  {key: "キャリアセンター", ans: "<a href='https://www.dokkyo.ac.jp/career/career_center/'>キャリアセンターについてはこちら</a>"},
  {key: "教職", ans: "<a href='https://www.dokkyo.ac.jp/career/teacher/'>教職・司書・日本語教員についてはこちら</a>"},
  {key: "司書", ans: "<a href='https://www.dokkyo.ac.jp/career/teacher/'>教職・司書・日本語教員についてはこちら</a>"},
  {key: "日本語教員", ans: "<a href='https://www.dokkyo.ac.jp/career/teacher/'>教職・司書・日本語教員についてはこちら</a>"},
  {key: "講座情報", ans: "<a href='https://www.dokkyo.ac.jp/career/lecture/'>各種講座情報についてはこちら</a>"},
  {key: "国際交流センター", ans: "<a href='https://www.dokkyo.ac.jp/international/international_center/'>国際交流センターについてはこちら</a>"},
  {key: "留学", ans: "<a href='https://www.dokkyo.ac.jp/international/abroad_system/'>留学についてはこちら</a>"},
  {key: "ICZ", ans: "<a href='https://www.dokkyo.ac.jp/research/support_center/language/icz.html'>ICZについてはこちら</a>"},
  {key: "icz", ans: "<a href='https://www.dokkyo.ac.jp/research/support_center/language/icz.html'>ICZについてはこちら</a>"},
  {key: "CLEAS", ans: "<a href='https://www.dokkyo.ac.jp/research/support_center/support/cleas.html'>CLEASについてはこちら</a>"},
  {key: "cleas", ans: "<a href='https://www.dokkyo.ac.jp/research/support_center/support/cleas.html'>CLEASについてはこちら</a>"},
  {key: "クレアス", ans: "<a href='https://www.dokkyo.ac.jp/research/support_center/support/cleas.html'>CLEASについてはこちら</a>"},
  {key: "ラーニング・スクエア", ans: "<a href='https://www.dokkyo.ac.jp/research/support_center/support/learning_square.html'>ラーニング・スクエアについてはこちら</a>"},
  {key: "ラーニングスクエア", ans: "<a href='https://www.dokkyo.ac.jp/research/support_center/support/learning_square.html'>ラーニング・スクエアについてはこちら</a>"},
  {key: "教育研究支援センター", ans: "<a href='https://www.dokkyo.ac.jp/research/support_center/info/explanation.html'>教育研究支援センターについてはこちら</a>"},
  {key: "奨学", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/scholarship/undergraduate.html'>奨学制度についてはこちら</a>"},
  {key: "フリースペース", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/facilities/free.html'>フリースペースについてはこちら</a>"},
  {key: "トレーニングルーム", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/facilities/training_room.html'>トレーニングルームについてはこちら</a>"},
  {key: "体育", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/facilities/sport_facility.html'>体育・スポーツ施設の利用についてはこちら</a>"},
  {key: "スポーツ", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/facilities/sport_facility.html'>体育・スポーツ施設の利用についてはこちら</a>"},
  {key: "理容室", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/facilities/barber.html'>理容室についてはこちら</a>"},
  {key: "バーバー獨協", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/facilities/barber.html'>理容室についてはこちら</a>"},
  {key: "オリンピック", ans: "<a href='https://www.dokkyo.ac.jp/about/outline/events/olympic/'>東京オリンピック・パラリンピックについてはこちら</a>"},
  {key: "時間", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/schedule/post_3.html'>授業時間帯についてはこちら</a>"},
  {key: "日程", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/schedule/event2021.html'>学事日程についてはこちら</a>"},
  {key: "カレンダー", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/schedule/2021.html'>キャンパスカレンダーについてはこちら</a>"},
  {key: "自転車", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/life/bicycle.html'>自転車通学についてはこちら</a>"},
  {key: "防犯", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/life/caution.html'>防犯についてはこちら</a>"},
  {key: "保険", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/life/gakkennsai.html'>保険についてはこちら</a>"},
  {key: "被災", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/life/disaster.html'>被災についてはこちら</a>"},
  {key: "分煙", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/life/nonsmokers.html'>分煙についてはこちら</a>"},
  {key: "保険センター", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/life/nonsmokers.html'>保健・安全衛生についてはこちら</a>"},
  {key: "カウンセリング", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/life/nonsmokers.html'>保健・安全衛生についてはこちら</a>"},
  {key: "防災", ans: "<a href='https://www.dokkyo.ac.jp/about/compliance/bousai/'>防災に関する取組みについてはこちら</a>"},
  {key: "寮", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/housing/'>学生寮・アパートについてはこちら</a>"},
  {key: "アパート", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/housing/'>学生寮・アパートについてはこちら</a>"},
  {key: "美術館", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/museum/'>美術館・博物館等の利用特典制度についてはこちら</a>"},
  {key: "博物館", ans: "<a href='https://www.dokkyo.ac.jp/campuslife/museum/'>美術館・博物館等の利用特典制度についてはこちら</a>"},
  {key: "大学の特長", ans: "<a href='https://www.dokkyo.ac.jp/about/outline/features/'>獨協大学の特長についてはこちら</a>"},
  {key: "大学の歴史", ans: "<a href='https://www.dokkyo.ac.jp/about/outline/history/principle/'>獨協大学の歴史についてはこちら</a>"},
  {key: "獨協の歴史", ans: "<a href='https://www.dokkyo.ac.jp/about/outline/history/principle/'>獨協大学の歴史についてはこちら</a>"},
  {key: "授業料", ans: "<a href='https://www.dokkyo.ac.jp/about/outline/history/principle/'>授業料・学費についてはこちら</a>"},
  {key: "学費", ans: "<a href='https://www.dokkyo.ac.jp/about/outline/history/principle/'>授業料・学費についてはこちら</a>"},
  {key: "所在地", ans: "獨協大学の所在地は<br><br>〒340-0042　埼玉県草加市学園町1番1号"},
  {key: "大学の住所", ans: "獨協大学の所在地は<br><br>〒340-0042　埼玉県草加市学園町1番1号"},
  {key: "教員", ans: "<a href='https://www.dokkyo.ac.jp/research/faculty/'>教員紹介はこちら</a>"},
  {key: "先生", ans: "<a href='https://www.dokkyo.ac.jp/research/faculty/'>教員紹介はこちら</a>"},
  {key: "教授", ans: "<a href='https://www.dokkyo.ac.jp/research/faculty/'>教員紹介はこちら</a>"},
  {key: "学則", ans: "<a href='https://www.dokkyo.ac.jp/about/openinfo/rules.html'>獨協大学学則はこちら</a>"},
  {key: "ポリシー", ans: "<a href='https://www.dokkyo.ac.jp/about/openinfo/policy/'>獨協大学・獨協大学大学院の３つのポリシー</a>"},
  {key: "大学院", ans: "<a href='https://www.dokkyo.ac.jp/academics/graduate/about/'>大学院についてはこちら</a>"},
  {key: "法学研究科", ans: "<a href='https://www.dokkyo.ac.jp/academics/graduate/law/'>法学研究科についてはこちら</a>"},
  {key: "外国語学研究科", ans: "<a href='https://www.dokkyo.ac.jp/academics/graduate/foreign_languages/'>外国語学研究科についてはこちら</a>"},
  {key: "経済学研究科", ans: "<a href='https://www.dokkyo.ac.jp/academics/graduate/economics/'>経済学研究科についてはこちら</a>"},
  {key: "入試", ans: "<a href='https://www.dokkyo.ac.jp/academics/graduate/examination/'>入試情報についてはこちら</a>"},
  {key: "全学共通", ans: "<a href='https://www.dokkyo.ac.jp/research/common_curriculum/'>全学共通カリキュラム</a>"},
  {key: "地域総合研究所", ans: "<a href='https://www.dokkyo.ac.jp/research/chiikiken/'>地域総合研究所についてはこちら</a>"},
  {key: "環境共生研究所", ans: "<a href='https://www.dokkyo.ac.jp/research/kankyoken/'>環境共生研究所についてはこちら</a>"},
  {key: "外国語教育研究所", ans: "<a href='https://www.dokkyo.ac.jp/research/amanoken/'>外国語教育研究所についてはこちら</a>"},
  {key: "経済学研究科", ans: "<a href='https://www.dokkyo.ac.jp/academics/graduate/economics/'>経済学研究科についてはこちら</a>"},
  {key: "情報学研究所", ans: "<a href='https://www.dokkyo.ac.jp/research/johoken/'>情報学研究所についてはこちら</a>"},
  {key: "獨協", ans: "<a href='https://www.dokkyo.ac.jp/'>大学HPはこちら</a>"},
];

  //チャットボット返信
  function write_message(){
    var message = document.getElementById("message").value;
    if(message != '') {
      document.getElementById("message").value = '';
      $('.chat_container').append("<div class='chat_right'><p class='post_date_right'></p><p class='right_balloon'>"+message.replace(/\n|\r\n|\r/g, '<br>')+"</p><br class='clear_balloon'/></div>");
      var element = document.documentElement;
      var bottom = element.scrollHeight - element.clientHeight;
      window.scroll(0, bottom);
      if(bot_dictionary.some((u) => ~message.indexOf(u.key))){
        var dokuta_answer = bot_dictionary.find((u) => ~message.indexOf(u.key));
        setTimeout(function(){
        $('.chat_container').append("<p class='name'>どく太くん</p><div class='chat_left'><img class='icon_img' src='img/dokuta.jpeg'><p class='left_balloon'>"+dokuta_answer['ans']+"</p><br class='clear_balloon'/></div>");
        var element = document.documentElement;
        var bottom = element.scrollHeight - element.clientHeight;
        window.scroll(0, bottom);
      },1000);
      }else {
        setTimeout(function(){
          $('.chat_container').append("<p class='name'>どく太くん</p><div class='chat_left'><img class='icon_img' src='img/dokuta.jpeg'><p class='left_balloon'>うーん、難しい…</p><br class='clear_balloon'/></div>");
          $('.chat_container').append("<p class='name'>どく太くん</p><div class='chat_left'><img class='icon_img' src='img/dokuta.jpeg'><p class='left_balloon'>履修登録、PorTaⅡ、図書館などについて聞いてほしい！</p><br class='clear_balloon'/></div>");
          var element = document.documentElement;
          var bottom = element.scrollHeight - element.clientHeight;
          window.scroll(0, bottom);
        },1000);
      }
  }
}